version: 2.1  

jobs:
  build_containers:
    machine:
      image: ubuntu-2204:2022.07.1
      docker_layer_caching: true
    parallelism: 3
    parameters:
      environment:
        type: string
    steps: 
      - checkout
      -  run: |
          tag=<<parameters.environment>>-$CIRCLE_SHA1
          docker build -t $tag . 
      - save_cache:
          key: docker-{{ checksum "Dockerfile" }}
          paths:
            - /tmp/docker

workflows:
  build:
    jobs:
      - build_containers:
          matrix:
            parameters:
              environment: ["dev", "qa", "prod"]